export { calculateStatistics } from './calculateStatistics';
export type {
  AuditTrailEntry,
  CagrData,
  CagrPoint,
  CalculateStatisticsOptions,
  CalculateStatisticsResult,
  CorrelationData,
  DataRow,
  GroupAggregateData,
  GroupAggregateEntry,
  GroupAggregation,
  GrowthRateData,
  GrowthRateMode,
  GrowthRatePoint,
  MathStatisticsError,
  MathStatisticsMetadata,
  MathStatisticsOperation,
  MathStatisticsWarning,
  OutlierIqrExample,
  OutliersIqrData,
  PercentileData,
  Severity,
  SummaryStatistics,
  SummaryStatisticsData,
  ToolEnvelope,
  ZScoreData,
  ZScoreRow,
} from './types';
